# Generated by Django 5.2.1 on 2025-10-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='apellido_materno',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='apellido_paterno',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='dni',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombres',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
