# Generated by Django 5.2.1 on 2025-10-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_alter_afiliado_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='apellido_paterno',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombres',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
