# Generated by Django 5.2.7 on 2025-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliados", "0002_atencion_registrado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="afiliado",
            name="observacion_enfermeria",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="afiliado",
            name="observacion_obstetricia",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="afiliado",
            name="observacion_odontologia",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
