# Generated by Django 6.0.3 on 2026-03-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_afiliado_observacion_enfermeria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
