# Generated by Django 6.0.3 on 2026-04-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_alter_afiliado_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
